# Generated by Django 5.2.4 on 2025-07-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='duenio',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ambientes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='patio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
