# Generated by Django 5.2.4 on 2025-07-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_propiedad_duenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='zona',
            field=models.CharField(default='Sin zona', max_length=50),
        ),
    ]
