# Generated by Django 5.2.1 on 2025-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_autor_remove_post_categoria_propiedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='direccion',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubicacion',
            field=models.CharField(default='Buenos Aires', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
