# Generated by Django 5.2.1 on 2025-07-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='fecha_envio',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Buenos Aires', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
